{% set version = "1.4-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sombrero
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SOMbrero_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SOMbrero/SOMbrero_{{ version }}.tar.gz
  sha256: e2b2364da9f68dd34ed7190138b5f5d8c34fe9f8fdd8be3f151f1e0372473c2d

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-ggwordcloud
    - r-igraph >=1.0
    - r-interp
    - r-markdown
    - r-metr
    - r-scatterplot3d
    - r-shiny
  run:
    - r-base
    - r-ggplot2
    - r-ggwordcloud
    - r-igraph >=1.0
    - r-interp
    - r-markdown
    - r-metr
    - r-scatterplot3d
    - r-shiny

test:
  commands:
    - $R -e "library('SOMbrero')"           # [not win]
    - "\"%R%\" -e \"library('SOMbrero')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SOMbrero
  license: GPL-2.0-or-later
  summary: The stochastic (also called on-line) version of the Self-Organising Map (SOM) algorithm is provided. Different versions of the algorithm are implemented, for numeric and relational data and for contingency tables as described, respectively, in Kohonen (2001) <isbn:3-540-67921-9>, Olteanu & Villa-Vialaneix (2005)
    <doi:10.1016/j.neucom.2013.11.047> and Cottrell et al (2004) <doi:10.1016/j.neunet.2004.07.010>. The package also contains many plotting features (to help the user interpret the results) and a graphical user interface based on 'shiny'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: SOMbrero
# Title: SOM Bound to Realize Euclidean and Relational Outputs
# Version: 1.2-4
# Date: 2019-03-07
# Authors@R: c(person("Nathalie", "Vialaneix", role = c("aut", "cre"), email="nathalie.vialaneix@inra.fr"), person("Jerome", "Mariette", role= "aut", email="jerome.mariette@inra.fr"), person("Madalina", "Olteanu", role = "aut", email="madalina.olteanu@univ-paris1.fr"), person("Fabrice", "Rossi", role = "aut", email="fabrice.rossi@univ-paris1.fr"), person("Laura", "Bendhaiba", role = "ctb", email="laurabendhaiba@gmail.com"), person("Julien", "Boelaert", role= "ctb", email="julien.boelaert@gmail.com"))
# Maintainer: Nathalie Vialaneix <nathalie.vialaneix@inra.fr>
# Description: The stochastic (also called on-line) version of the Self-Organising Map (SOM) algorithm is provided. Different versions of the algorithm are implemented, for numeric and relational data and for contingency tables as described, respectively, in Kohonen (2001) <isbn:3-540-67921-9>, Olteanu & Villa-Vialaneix (2005) <doi:10.1016/j.neucom.2013.11.047> and Cottrell et al (2004) <doi:10.1016/j.neunet.2004.07.010>. The package also contains many plotting features (to help the user interpret the results) and a graphical user interface based on 'shiny'.
# BugReports: http://github.com/tuxette/sombrero/issues
# Depends: R (>= 3.1.0), igraph (>= 1.0)
# Imports: wordcloud, scatterplot3d, RColorBrewer, shiny, grDevices, graphics, stats
# Suggests: testthat, rmarkdown, knitr
# License: GPL (>= 2)
# Repository: CRAN
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-07 16:18:07 UTC; nathalie
# Author: Nathalie Vialaneix [aut, cre], Jerome Mariette [aut], Madalina Olteanu [aut], Fabrice Rossi [aut], Laura Bendhaiba [ctb], Julien Boelaert [ctb]
# Date/Publication: 2019-03-07 17:32:51 UTC
