appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: P271Q/gXmy7/ZUAY+e1V6n6/D5x4VrMul/yC49H6M9UdmvAu/JuAqadKz5gAwWZk0Ym9BP+ryqRLgYM79DmoukHGosEOFmbcqqguHCQXXYsuQayb+CJDedeg9XF+Tfql/Qri9Dwfj4HYrKKSGq0P3b7bx3XrlU4dy29lk8kVQS524PqNT/tRD8JnXlMllGnNVhzJ4FQzPqlThAdauNvaINPWv/JYcZdT6zZGx0ZHBj/4/7MFYVzcDKAaprv7u0sL1KIpCBfh586sOwpNhpWN+83rZdOyie9J56+W+Tx/Qo5NnPt0RmMzZKSvoataD+E7T8H3SXbaFqC/PcVx/D1pStiJGZ2Vfl/tPaNiioyDncM8MvAYA1ACQz+CDTe+TpQzWPMaOes+8CIseQ98XHERcZOzvTduBzbQT5rwXFz9a9UuuHG8VqXEGobylisF3YWyzTsULlGoNOzovXgqAyCAlzYM8qglump+PKguAs+0QvgK8Qg4965LJ6cy9M2eU6Q8fFBum6rVOkhaZHHjISWYEldHOizigA3XZx1SX1gTgl0kYYrEA/gjlFTzB7Dg1as7jW/x5MSirqhcQF1FYwawJNsbiy6TE84CmLejP0h3Za1iGZF83DahkqxR3XRXRxW5mYeHi+ZLyE6dgffS2ZROdyHk5V5jZozCqZgLdG+twx0=
conda_forge_output_validation: false
